version: '2'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE1: notes_app_dev
      MYSQL_USER1: notes_app_admin
      MYSQL_PASSWORD1: pass
      MYSQL_DATABASE2: notes_app_test
      MYSQL_USER: notes_app_admin
      MYSQL_PASSWORD: pass
      MYSQL_USER2: notes_app_admin
      MYSQL_PASSWORD2: pass
    ports:
      - "3306:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/notes_app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_PASSWORD: pass
      DB_DATABASE: notes_app_dev
      DB_USER: notes_app_admin
      DB_HOST: db
