#!/bin/bash
echo "Preparing System:"
echo ""

echo "Installing ruby2.4.0..."
echo ""
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL
rbenv install 2.4.0
rbenv global 2.4.0

echo "Installing docker-compose..."
echo ""
sudo apt-get -y install python-pip
sudo pip install docker-compose

echo "Building: docker-compose build..."
echo ""
docker-compose build

echo "Launching services: docker-compose up..."
echo ""
docker-compose up -d

echo "."
sleep 2
echo ".."
sleep 2
echo "...."
sleep 2
echo "......"
sleep 2
echo "........"
sleep 2
echo ".........."

if docker-compose run --rm app rake db:migrate ; then
  echo ""
  echo "Notes App should be available at 139.59.170.157:3000!"
else
  echo ""
  echo "Something went wrong, make sure db and app containers are up and running and run again db:migrate"
fi
