development:
  DB_PASSWORD: pass
  DB_DATABASE: notes_app_dev
  DB_USER: notes_app_admin
  DB_HOST: localhost
  AWS_ACCESS_KEY: AKIAIYPPFGYWYBWPTGNQ
  AWS_SECRET_KEY: 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
  AWS_REGION: eu-west-1
  S3_BUCKET: testnotesapplication

production:
  DB_PASSWORD: pass
  DB_DATABASE: notes_app_dev
  DB_USER: notes_app_admin
  AWS_ACCESS_KEY: AKIAIYPPFGYWYBWPTGNQ
  AWS_SECRET_KEY: 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
  AWS_REGION: eu-west-1
  S3_BUCKET: testnotesapplication
